kind: Service
apiVersion: v1
metadata:
  name: nginx-example-service
spec:
  selector:
    app: nginx-example
  ports:
    - protocol: TCP
      targetPort: 80
      port: 80
      name: http
  type: NodePort
