apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: web
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30800
    name: http
  selector:
    app: nginx
