apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: web
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
      port: 80
      targetPort: 80
      nodePort: 31000
  selector:
    app: nginx
